language: go

go:
  - 1.0.x
  - 1.1.x
  - 1.2.x
  - 1.3.x
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - master

install:
  - go get -u github.com/alecthomas/gometalinter

script:
  - make compile
  - make test
  - make bench
  - make lint
