language: go

go:
#  - 1.2.x
#  - 1.3.x
#  - 1.4.x
#  - 1.5.x
#  - 1.6.x
  - 1.7.x
  - master

install:
  - go get -u github.com/cznic/golex
  - go get -u github.com/alecthomas/gometalinter
  - $GOPATH/bin/gometalinter --install

script:
  - make compile
  - make test
  - make bench
  - make lint
